version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      spring:
        patterns:
          - "org.springframework*"
      observability:
        patterns:
          - "io.micrometer*"
          - "com.datadoghq*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
