CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    sobrenome VARCHAR(120) NOT NULL,
    data_nascimento DATE NOT NULL,
    email VARCHAR(180) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    senha_hash VARCHAR(120) NOT NULL,
    agencia VARCHAR(10) NOT NULL,
    conta VARCHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_usuarios_email ON usuarios (email);
CREATE UNIQUE INDEX IF NOT EXISTS uk_usuarios_cpf ON usuarios (cpf);
CREATE UNIQUE INDEX IF NOT EXISTS uk_usuarios_agencia_conta ON usuarios (agencia, conta);
